name: 'Allure Report with history'
description: 'Generate Allure Report with history'
author: 'simple-elf'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  allure_results:
    description: 'Allure test result data dir'
    required: true
    default: 'allure-results'
  allure_report:
    description: 'Allure report target dir'
    required: true
    default: 'allure-report'
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  gh_pages_branch:
    description: 'gh-pages branch'
    required: true
    default: 'gh-pages'
  github_token:
    description: 'GitHub token'
    required: true
  allure_history:
    description: 'Folder for allure history'
    required: true
    default: 'allure-history'
  subfolder:
    description: 'subfolder'
    required: false
    default: ''
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  github_repo:
    description: 'GitHub repository'
    required: true
    default: ${{ github.repository }}
  github_repo_owner:
    description: 'GitHub repository owner'
    required: true
    default: ${{ github.repository_owner }}
  github_tests_repo:
    description: 'GitHub repository where test are run'
    required: true
    default: ${{ github.repository }}
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: ''
  github_server_url:
    description: 'GitHub server URL'
    required: true
    default: ${{ github.server_url }}


runs:
  using: 'composite'
  steps:
    - name: Set Up Environment Variables
      shell: bash
      env:
        INPUT_ALLURE_RESULTS: '${{ inputs.allure_results }}'
        INPUT_ALLURE_REPORT: '${{ inputs.allure_report }}'
        INPUT_GH_PAGES: '${{ inputs.gh_pages }}'
        INPUT_GH_PAGES_BRANCH: '${{ inputs.gh_pages_branch }}'
        INPUT_ALLURE_HISTORY: '${{ inputs.allure_history }}'
        INPUT_SUBFOLDER: '${{ inputs.subfolder }}'
        INPUT_KEEP_REPORTS: '${{ inputs.keep_reports }}'
        INPUT_GITHUB_RUN_NUM: '${{ inputs.github_run_num }}'
        INPUT_GITHUB_RUN_ID: '${{ inputs.github_run_id }}'
        GIT_TOKEN: '${{ inputs.github_token }}'
        INPUT_GITHUB_REPO: '${{ inputs.github_repo }}'
        INPUT_GITHUB_REPO_OWNER: '${{ inputs.github_repo_owner }}'
        INPUT_GITHUB_TESTS_REPO: '${{ inputs.github_tests_repo }}'
        INPUT_REPORT_URL: '${{ inputs.report_url }}'
        INPUT_GITHUB_SERVER_URL: '${{ inputs.github_server_url }}'
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        sh ${{ github.action_path }}/entrypoint.sh
